// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odcrvscotczvrqsjrwpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kY3J2c2NvdGN6dnJxc2pyd3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzMxNjYsImV4cCI6MjA2NzkwOTE2Nn0.AMOrMvdGi6-5LXNuspiaiqIqOf5blBNrpgWjUEGwmlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});